### ISSUE TITLE
Dependency not found

### ISSUE THREAD

**Issue by davidma17** [manishkummar21/bluetoothscanning#1]
I followed the instructions given in the README but when I try to build my file, it gives me the following error:

Could not find com.github.manishkummar21:bluetoothscanning:Tag.

What should I do from here?

**Comment by manishkummar21** [comment]
Tag means version 

please replace with this 
implementation 'com.github.manishkummar21:bluetoothscanning:v1.0'

**Comment by manishkummar21** [comment]
Thanks i will update
